#!/usr/bin/env node
/* =============================================================================
   motion-tokens.mjs — generate motion/micro-interaction tokens
   ============================================================================= */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

export const MOTION_TOKENS = {
  /* Duration scale */
  '--duration-fast': '0.1s',
  '--duration-normal': '0.2s',
  '--duration-slow': '0.3s',
  '--duration-slower': '0.5s',

  /* Easing scale */
  '--ease-smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',           // smooth deceleration
  '--ease-sharp': 'cubic-bezier(0.4, 0, 0.2, 1)',             // same as smooth (shadcn default)
  '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',                   // accelerate
  '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',                  // decelerate
  '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',             // accelerate then decelerate
  '--ease-spring': 'cubic-bezier(0.34, 1.4, 0.5, 1)',          // bouncy overshoot (moss)
  '--ease-spring-out': 'cubic-bezier(0.34, 1.56, 0.64, 1)',   // strong bouncy
  '--ease-spring-in': 'cubic-bezier(0.34, -0.6, 0.64, 1)',    // pull-back
  '--ease-bounce': 'cubic-bezier(0.68, -0.6, 0.32, 1.6)',     // big bounce

  /* Spacing for stagger/spacing patterns */
  '--spacing-stagger': '0.05s',
};

// Generate CSS file with all motion tokens
const css = `/* motion.css — DG motion tokens */
/* Generated by tools/motion-tokens.mjs */
:root {
${Object.entries(MOTION_TOKENS).map(([k, v]) => `  ${k.padEnd(22)}: ${v};`).join('\n')}
}
`;

// Write to src/tokens/
const out = path.join(ROOT, 'src', 'tokens', 'motion.css');
fs.writeFileSync(out, css);

console.log(`  ✓ Motion tokens → src/tokens/motion.css (${Object.keys(MOTION_TOKENS).length} tokens)`);
